# Generated by Django 6.0 on 2025-12-15 22:41

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona_external', models.CharField(help_text='UUID externo de la persona en el módulo de usuarios', max_length=100, unique=True, verbose_name='External ID Persona')),
                ('cargo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
                'db_table': 'administrador',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona_external', models.CharField(help_text='UUID externo de la persona en el módulo de usuarios', max_length=100, unique=True, verbose_name='External ID Persona')),
                ('especialidad', models.CharField(max_length=100, verbose_name='Especialidad')),
                ('club_asignado', models.CharField(max_length=100, verbose_name='Club asignado')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Entrenador',
                'verbose_name_plural': 'Entrenadores',
                'db_table': 'entrenador',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Pasante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona_external', models.CharField(help_text='UUID externo de la persona en el módulo de usuarios', max_length=100, unique=True, verbose_name='External ID Persona')),
                ('carrera', models.CharField(max_length=100, verbose_name='Carrera')),
                ('semestre', models.CharField(max_length=20, verbose_name='Semestre')),
                ('universidad', models.CharField(blank=True, max_length=150, null=True, verbose_name='Universidad')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio de vinculación')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de fin de vinculación')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Pasante',
                'verbose_name_plural': 'Pasantes',
                'db_table': 'pasante',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='GrupoAtleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('rango_edad_minima', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Rango edad mínima')),
                ('rango_edad_maxima', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Rango edad máxima')),
                ('categoria', models.CharField(max_length=50, verbose_name='Categoría')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos', to='basketball.entrenador', verbose_name='Entrenador')),
            ],
            options={
                'verbose_name': 'Grupo de Atleta',
                'verbose_name_plural': 'Grupos de Atletas',
                'db_table': 'grupo_atleta',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_atleta', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido_atleta', models.CharField(max_length=100, verbose_name='Apellido')),
                ('dni', models.CharField(max_length=20, unique=True, verbose_name='DNI')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('edad', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Edad')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Sexo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('tipo_sangre', models.CharField(blank=True, max_length=10, null=True, verbose_name='Tipo de sangre')),
                ('datos_representante', models.TextField(blank=True, null=True, verbose_name='Datos del representante')),
                ('telefono_representante', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono representante')),
                ('foto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Foto')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('grupos', models.ManyToManyField(blank=True, related_name='atletas', to='basketball.grupoatleta', verbose_name='Grupos')),
            ],
            options={
                'verbose_name': 'Atleta',
                'verbose_name_plural': 'Atletas',
                'db_table': 'atleta',
                'ordering': ['apellido_atleta', 'nombre_atleta'],
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(verbose_name='Fecha de inscripción')),
                ('tipo_inscripcion', models.CharField(choices=[('FEDERADO', 'Federado'), ('NO_FEDERADO', 'No Federado'), ('INVITADO', 'Invitado')], max_length=20, verbose_name='Tipo de inscripción')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('habilitada', models.BooleanField(default=True, verbose_name='Habilitada')),
                ('registrado_por', models.CharField(blank=True, max_length=100, null=True, verbose_name='Registrado por (External ID)')),
                ('atleta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inscripcion', to='basketball.atleta', verbose_name='Atleta')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'db_table': 'inscripcion',
                'ordering': ['-fecha_inscripcion'],
            },
        ),
        migrations.CreateModel(
            name='PruebaAntropometrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(verbose_name='Fecha de registro')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Peso (kg)')),
                ('estatura', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Estatura (cm)')),
                ('indice_masa_corporal', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Índice de masa corporal')),
                ('altura_sentado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Altura sentado (cm)')),
                ('envergadura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Envergadura (cm)')),
                ('indice_cornico', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Índice córnico')),
                ('porcentaje_grasa', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Porcentaje de grasa corporal')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('registrado_por', models.CharField(blank=True, max_length=100, null=True, verbose_name='Registrado por (External ID)')),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pruebas_antropometricas', to='basketball.atleta', verbose_name='Atleta')),
            ],
            options={
                'verbose_name': 'Prueba Antropométrica',
                'verbose_name_plural': 'Pruebas Antropométricas',
                'db_table': 'prueba_antropometrica',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='PruebaFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(verbose_name='Fecha de registro')),
                ('tipo_prueba', models.CharField(choices=[('VELOCIDAD', 'Velocidad'), ('RESISTENCIA', 'Resistencia'), ('FUERZA', 'Fuerza'), ('FLEXIBILIDAD', 'Flexibilidad'), ('COORDINACION', 'Coordinación'), ('AGILIDAD', 'Agilidad')], max_length=20, verbose_name='Tipo de prueba')),
                ('nombre_prueba', models.CharField(max_length=100, verbose_name='Nombre de la prueba')),
                ('resultado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Resultado')),
                ('unidad_medida', models.CharField(max_length=20, verbose_name='Unidad de medida')),
                ('valoracion', models.CharField(blank=True, help_text='Ej: Excelente, Bueno, Regular, Deficiente', max_length=50, null=True, verbose_name='Valoración')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('registrado_por', models.CharField(blank=True, max_length=100, null=True, verbose_name='Registrado por (External ID)')),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pruebas_fisicas', to='basketball.atleta', verbose_name='Atleta')),
            ],
            options={
                'verbose_name': 'Prueba Física',
                'verbose_name_plural': 'Pruebas Físicas',
                'db_table': 'prueba_fisica',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
